name: Check PR

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable

      - name: Check Prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:prettier

      - name: Check ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:eslint

      - name: Check TypeScript
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ts

      - name: Check Vite build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
