name: Deploy on VM

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable

      - name: Run yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Remove existing production build
        run: rm -rf ~/production/frontend
      - name: Create a directory for production build (if missing)
        run: mkdir -p ~/production/frontend
      - name: Copy production build
        run: cp -rf ./dist/. ~/production/frontend
